- id: go-test
  name: 'Go tests'
  entry: run-go-test.sh
  types: [go]
  language: 'script'
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: "Runs `go test ./...` at the repo root"

- id: goimports
  name: 'Check Go imports'
  entry: run-go-imports.sh
  types: [go]
  language: 'script'
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  description: "Runs `goimports` on changed files"
  require_serial: true
  exclude: 'vendor/'

- id: dep-check
  name: 'dep-check'
  entry: run-dep-check.sh
  types: [go]
  language: 'script'
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: "Runs `dep check`, ensuring all imports are vendored"

- id: todo-jira-check
  name: 'TODOs have JIRA tags'
  entry: todo-jira-check.py
  types: [text]
  language: 'script'
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  exclude: 'vendor/'
  description: "Checks changes contain only TODOs with JIRA tags"

- id: branch-name-check
  name: 'branch name begin with (feature|bugfix|release|hotfix)'
  entry: run-branch-name-check.sh
  types: [text]
  language: 'script'
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  description: "Checks branch names adhere to the regex ^(feature|bugfix|release|hotfix)\/[a-z0-9._-]+$"