- id: todo-tagged-jira
  name: 'TODOs have JIRA tags'
  entry: todo-jira-check.py
  types: [text]
  language: 'script'
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  exclude: 'vendor/'
  description: "Checks changes contain only TODOs with JIRA tags"

- id: todo-branch-tags
  name: 'Outstanding TODOs for the current branch'
  entry: run-find-branch-todos.sh
  always_run: true
  language: 'script'
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: 'Prints any TODOs tagged with the ticket reference in the current branch name'

- id: branch-name-check
  name: 'Branch name obeys the standardised format'
  entry: run-branch-name-check.sh
  always_run: true
  pass_filenames: false
  language: 'script'
  minimum_pre_commit_version: 0.15.0
  description: 'Checks branch names obeys the following regex'

- id: go-test
  name: 'Go tests'
  entry: run-go-test.sh
  types: [go]
  language: 'script'
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: "Runs `go test ./...` at the repo root"

- id: go-goimports
  name: 'Check Go imports'
  entry: run-go-imports.sh
  types: [go]
  language: 'script'
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  description: "Runs `goimports` on changed files"
  require_serial: true
  exclude: 'vendor/'

- id: go-dep-check
  name: 'Dependencies are vendored (dep)'
  entry: run-dep-check.sh
  types: [go]
  language: 'script'
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: "Runs `dep check`, ensuring all imports are vendored"

# A copy of
# https://github.com/golangci/golangci-lint/commit/09677d574ea6cd05141022aa90b88b6598bfa1a1
# without --fix forced on users.
- id: go-golangci-lint
  name: 'Run golangci-lint'
  description: Static analysis for Go code
  entry: golangci-lint run
  types: [go]
  language: golang
  pass_filenames: false

- id: rust-clippy
  name: 'Run clippy lints'
  entry: run-rust-clippy.sh
  language: 'script'
  files: Cargo\.toml|\.rs$
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: 'Run clippy lints against rust code'

- id: rust-test
  name: 'Cargo tests'
  entry: run-rust-tests.sh
  language: 'script'
  files: \.rs$
  pass_filenames: false
  minimum_pre_commit_version: 0.15.0
  description: 'Run cargo test in the repo root'

- id: r-stylr
  name: 'Format with stylr'
  entry: run-r-stylr.R
  language: 'script'
  files: (?i)\.R$
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  description: 'Run stylr to format R code'

- id: r-lintr
  name: 'Analyse with lintr'
  entry: run-r-lintr.R
  language: 'script'
  files: (?i)\.R$
  pass_filenames: true
  minimum_pre_commit_version: 0.15.0
  description: 'Run lintr against R code'